"""
Container execution module for LiteCodeAgent.

This package provides classes and utilities for executing code in isolated container environments,
ensuring that code generated by LLMs runs securely without direct access to the host system.
"""

from .executor import ContainerExecutor, DockerExecutor, PodmanExecutor, ContainerFactory

__all__ = [
    'ContainerExecutor',
    'DockerExecutor',
    'PodmanExecutor',
    'ContainerFactory',
]